config/routes.rb
Rails.application.routes.draw do
  resources :expedients
  resources :destinations
  resources :responsibles
  resources :exp_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/exp_types_controller.rb
class ExpTypesController < ApplicationController
  before_action :set_exp_type, only: [:show, :edit, :update, :destroy]

  # GET /exp_types
  # GET /exp_types.json
  def index
    @exp_types = ExpType.all
  end

  # GET /exp_types/1
  # GET /exp_types/1.json
  def show
  end

  # GET /exp_types/new
  def new
    @exp_type = ExpType.new
  end

  # GET /exp_types/1/edit
  def edit
  end

  # POST /exp_types
  # POST /exp_types.json
  def create
    @exp_type = ExpType.new(exp_type_params)

    respond_to do |format|
      if @exp_type.save
        format.html { redirect_to @exp_type, notice: 'Exp type was successfully created.' }
        format.json { render :show, status: :created, location: @exp_type }
      else
        format.html { render :new }
        format.json { render json: @exp_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exp_types/1
  # PATCH/PUT /exp_types/1.json
  def update
    respond_to do |format|
      if @exp_type.update(exp_type_params)
        format.html { redirect_to @exp_type, notice: 'Exp type was successfully updated.' }
        format.json { render :show, status: :ok, location: @exp_type }
      else
        format.html { render :edit }
        format.json { render json: @exp_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exp_types/1
  # DELETE /exp_types/1.json
  def destroy
    @exp_type.destroy
    respond_to do |format|
      format.html { redirect_to exp_types_url, notice: 'Exp type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exp_type
      @exp_type = ExpType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exp_type_params
      params.require(:exp_type).permit(:description)
    end
end

app/helpers/exp_types_helper.rb
module ExpTypesHelper
end

app/views/exp_types/_form.html.erb
<%= form_with(model: exp_type, local: true) do |form| %>
  <% if exp_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exp_type.errors.count, "error") %> prohibited this exp_type from being saved:</h2>

      <ul>
      <% exp_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/exp_types/edit.html.erb
<h1>Editing Exp Type</h1>

<%= render 'form', exp_type: @exp_type %>

<%= link_to 'Show', @exp_type %> |
<%= link_to 'Back', exp_types_path %>

app/views/exp_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Exp Types</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exp_types.each do |exp_type| %>
      <tr>
        <td><%= exp_type.description %></td>
        <td><%= link_to 'Show', exp_type %></td>
        <td><%= link_to 'Edit', edit_exp_type_path(exp_type) %></td>
        <td><%= link_to 'Destroy', exp_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Exp Type', new_exp_type_path %>

app/views/exp_types/new.html.erb
<h1>New Exp Type</h1>

<%= render 'form', exp_type: @exp_type %>

<%= link_to 'Back', exp_types_path %>

app/views/exp_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @exp_type.description %>
</p>

<%= link_to 'Edit', edit_exp_type_path(@exp_type) %> |
<%= link_to 'Back', exp_types_path %>