config/routes.rb
Rails.application.routes.draw do
  resources :expedients
  resources :destinations
  resources :responsibles
  resources :exp_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/responsible.rb
class Responsible < ApplicationRecord
    has_many :expedient
end

app/controllers/responsibles_controller.rb
class ResponsiblesController < ApplicationController
  before_action :set_responsible, only: [:show, :edit, :update, :destroy]

  # GET /responsibles
  # GET /responsibles.json
  def index
    @responsibles = Responsible.all
  end

  # GET /responsibles/1
  # GET /responsibles/1.json
  def show
  end

  # GET /responsibles/new
  def new
    @responsible = Responsible.new
  end

  # GET /responsibles/1/edit
  def edit
  end

  # POST /responsibles
  # POST /responsibles.json
  def create
    @responsible = Responsible.new(responsible_params)

    respond_to do |format|
      if @responsible.save
        format.html { redirect_to @responsible, notice: 'Responsible was successfully created.' }
        format.json { render :show, status: :created, location: @responsible }
      else
        format.html { render :new }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responsibles/1
  # PATCH/PUT /responsibles/1.json
  def update
    respond_to do |format|
      if @responsible.update(responsible_params)
        format.html { redirect_to @responsible, notice: 'Responsible was successfully updated.' }
        format.json { render :show, status: :ok, location: @responsible }
      else
        format.html { render :edit }
        format.json { render json: @responsible.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responsibles/1
  # DELETE /responsibles/1.json
  def destroy
    @responsible.destroy
    respond_to do |format|
      format.html { redirect_to responsibles_url, notice: 'Responsible was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_responsible
      @responsible = Responsible.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def responsible_params
      params.require(:responsible).permit(:description)
    end
end

app/helpers/responsibles_helper.rb
module ResponsiblesHelper
end

app/views/responsibles/_form.html.erb
<%= form_with(model: responsible, local: true) do |form| %>
  <% if responsible.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(responsible.errors.count, "error") %> prohibited this responsible from being saved:</h2>

      <ul>
      <% responsible.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/responsibles/edit.html.erb
<h1>Editing Responsible</h1>

<%= render 'form', responsible: @responsible %>

<%= link_to 'Show', @responsible %> |
<%= link_to 'Back', responsibles_path %>

app/views/responsibles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Responsibles</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responsibles.each do |responsible| %>
      <tr>
        <td><%= responsible.description %></td>
        <td><%= link_to 'Show', responsible %></td>
        <td><%= link_to 'Edit', edit_responsible_path(responsible) %></td>
        <td><%= link_to 'Destroy', responsible, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Responsible', new_responsible_path %>

app/views/responsibles/new.html.erb
<h1>New Responsible</h1>

<%= render 'form', responsible: @responsible %>

<%= link_to 'Back', responsibles_path %>

app/views/responsibles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @responsible.description %>
</p>

<%= link_to 'Edit', edit_responsible_path(@responsible) %> |
<%= link_to 'Back', responsibles_path %>