config/routes.rb
Rails.application.routes.draw do
  resources :expedients
  resources :destinations
  resources :responsibles
  resources :exp_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/expedient.rb
class Expedient < ApplicationRecord
  belongs_to :exp_type
  belongs_to :destination  #, optional: true
  belongs_to :responsible
end

app/controllers/expedients_controller.rb
class ExpedientsController < ApplicationController
  before_action :set_expedient, only: [:show, :edit, :update, :destroy]

  # GET /expedients
  # GET /expedients.json
  def index
    @expedients = Expedient.all
  end

  # GET /expedients/1
  # GET /expedients/1.json
  def show
  end

  # GET /expedients/new
  def new
    @expedient = Expedient.new
  end

  # GET /expedients/1/edit
  def edit
  end

  # POST /expedients
  # POST /expedients.json
  def create
    @expedient = Expedient.new(expedient_params)

    respond_to do |format|
      if @expedient.save
        format.html { redirect_to @expedient, notice: 'Expedient was successfully created.' }
        format.json { render :show, status: :created, location: @expedient }
      else
        format.html { render :new }
        format.json { render json: @expedient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expedients/1
  # PATCH/PUT /expedients/1.json
  def update
    respond_to do |format|
      if @expedient.update(expedient_params)
        format.html { redirect_to @expedient, notice: 'Expedient was successfully updated.' }
        format.json { render :show, status: :ok, location: @expedient }
      else
        format.html { render :edit }
        format.json { render json: @expedient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expedients/1
  # DELETE /expedients/1.json
  def destroy
    @expedient.destroy
    respond_to do |format|
      format.html { redirect_to expedients_url, notice: 'Expedient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expedient
      @expedient = Expedient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def expedient_params
      params.require(:expedient).permit(:date_exp, :topic, :spu, :exp_type_id, :destination_id, :responsible_id)
    end
end

app/helpers/expedients_helper.rb
module ExpedientsHelper
end

app/views/expedients/_form.html.erb
<%= form_with(model: expedient, local: true) do |form| %>
  <% if expedient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expedient.errors.count, "error") %> prohibited this expedient from being saved:</h2>

      <ul>
      <% expedient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
      <div class="row">
        <div class="col-sm">
        <%= form.label "Data" %>
        <%= form.text_field :date_exp %>
        </div>
        <div class="col-sm">
        <%= form.label "Destino" %>   
        <%= collection_select(:expedient, :destination_id, Destination.all, :id, :description ,  prompt: 'Selecione um destino') %>  
        </div>
        <div class="col-sm">
        <%= form.label "Responsável" %>
        <%= collection_select(:expedient, :responsible_id, Responsible.all, :id, :description) %>  
        </div>
        <div class="col-sm">
        <%= form.label "Tipo" %>
        <%= collection_select(:expedient, :exp_type_id, ExpType.all, :id, :description ,  prompt: 'Selecione um tipo') %>  
        </div>
      </div>
</div>

<div class="container">
  <div class="row">
    <div class="col">
    <%= form.label "Assunto" %>
    <%= form.text_field :topic %>
    </div>
  </div>
</div>


<div class="container">
  <div class="row">
    <div class="col">
    <%= form.label "SPU" %>
    <%= form.text_field :spu %>
    </div>
  </div>
</div>
        
  <div class="field">
    <%= form.label "Data" %>
    <%= form.text_field :date_exp %>
  </div>

  <div class="field">
    <%= form.label "Assunto" %>
    <%= form.text_field :topic %>
  </div>

  <div class="field">
    <%= form.label "SPU" %>
    <%= form.text_field :spu %>
  </div>

  <div class="field">
    <%= form.label "Tipo" %>
    <%= collection_select(:expedient, :exp_type_id, ExpType.all, :id, :description ,  prompt: 'Selecione um tipo') %>  
  </div>

  <div class="field">
  
  <%= form.label "Destino" %>   
  <%= collection_select(:expedient, :destination_id, Destination.all, :id, :description ,  prompt: 'Selecione um destino') %>  
      
  </div>

  <div class="field">
    <%= form.label "Responsável" %>
    <%= collection_select(:expedient, :responsible_id, Responsible.all, :id, :description) %>  
  </div>

  <div class="actions">
    <%= form.submit "Cadastrar" %>
  </div>

  <button type="submit" class="btn btn-info ">Cadastrar</button>
<% end %>

app/views/expedients/edit.html.erb
<h1>Editing Expedient</h1>

<%= render 'form', expedient: @expedient %>

<%= link_to 'Show', @expedient %> |
<%= link_to 'Back', expedients_path %>

app/views/expedients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expedientes</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Assunto</th>
      <th>SPU</th>
      <th>Tipo</th>
      <th>Destino</th>
      <th>Responsável</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expedients.each do |expedient| %>
      <tr>
        <td><%= expedient.date_exp %></td>
        <td><%= expedient.topic %></td>
        <td><%= expedient.spu %></td>
        <td><%= expedient.exp_type_id %></td>
        <td><%= expedient.destination_id %></td>
        <td><%= expedient.responsible_id %></td>
        <td><%= link_to 'Show', expedient %></td>
        <td><%= link_to 'Edit', edit_expedient_path(expedient) %></td>
        <td><%= link_to 'Destroy', expedient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expedient', new_expedient_path %>

app/views/expedients/new.html.erb
<nav class="nav">
  <a class="nav-link active" href="#">Active</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link" href="#">Link</a>
  <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
</nav>

<h1>Expediente</h1>

<%= render 'form', expedient: @expedient %>

<%= link_to 'Back', expedients_path %>

app/views/expedients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date exp:</strong>
  <%= @expedient.date_exp %>
</p>

<p>
  <strong>Topic:</strong>
  <%= @expedient.topic %>
</p>

<p>
  <strong>Spu:</strong>
  <%= @expedient.spu %>
</p>

<p>
  <strong>Exp type:</strong>
  <%= @expedient.exp_type_id %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @expedient.destination_id %>
</p>

<p>
  <strong>Responsible:</strong>
  <%= @expedient.responsible_id %>
</p>

<%= link_to 'Edit', edit_expedient_path(@expedient) %> |
<%= link_to 'Back', expedients_path %>